//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.09 at 10:08:40 PM SAMT 
//


package ru.gvg.spring.soap.task;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gvg.spring.soap.task package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gvg.spring.soap.task
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link CreateTaskRequest }
     * 
     */
    public CreateTaskRequest createCreateTaskRequest() {
        return new CreateTaskRequest();
    }

    /**
     * Create an instance of {@link CreateTaskResponse }
     * 
     */
    public CreateTaskResponse createCreateTaskResponse() {
        return new CreateTaskResponse();
    }

    /**
     * Create an instance of {@link RemoveTaskRequest }
     * 
     */
    public RemoveTaskRequest createRemoveTaskRequest() {
        return new RemoveTaskRequest();
    }

    /**
     * Create an instance of {@link RemoveTaskResponse }
     * 
     */
    public RemoveTaskResponse createRemoveTaskResponse() {
        return new RemoveTaskResponse();
    }

    /**
     * Create an instance of {@link GetTasksRequest }
     * 
     */
    public GetTasksRequest createGetTasksRequest() {
        return new GetTasksRequest();
    }

    /**
     * Create an instance of {@link GetTasksResponse }
     * 
     */
    public GetTasksResponse createGetTasksResponse() {
        return new GetTasksResponse();
    }

    /**
     * Create an instance of {@link TaskRecord }
     * 
     */
    public TaskRecord createTaskRecord() {
        return new TaskRecord();
    }

    /**
     * Create an instance of {@link ResultRecord }
     * 
     */
    public ResultRecord createResultRecord() {
        return new ResultRecord();
    }

}
