//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.09 at 10:08:40 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gvg.ru/spring/soap/task", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gvg.spring.soap.task;
